### ISSUE TITLE
Procedure to add new plugins

### ISSUE THREAD

**Issue by whysthatso** [cabotapp/docker-cabot#26]
I've followed the steps to add a new plugin:
1. create own dockerfile
```
FROM cabotapp/cabot:0.11.13
RUN pip install cabot_alert_telegram
```
1. build a new container
```
docker build -t foobar/cabot:latest .
```
1. verified that pip install worked
```
docker run -it  foobar/cabot:latest /bin/sh
pip freeze
```

output

```
...
botocore==1.10.26
cabot==0.11.13
cabot-alert-email==1.4.3
cabot-alert-hipchat==2.0.3
cabot-alert-slack==0.8.3
cabot-alert-telegram==0.6
cabot-alert-twilio==1.3.3
cabot-check-cloudwatch==0.1.2
celery==4.0.2
...
```

1. adjusted the docker-compose file to reference the new image

```
web:
    image: foobar/cabot:latest
```
1. adjusted the conf/default.env file to add the new plugin

```
CABOT_PLUGINS_ENABLED=cabot_alert_email, cabot_alert_telegram
```

1. get this error

```
web_1       | Traceback (most recent call last):
web_1       |   File "/usr/local/bin/cabot", line 11, in <module>
web_1       |     sys.exit(main())
web_1       |   File "/usr/local/lib/python2.7/site-packages/cabot/entrypoint.py", line 10, in main
web_1       |     execute_from_command_line(sys.argv)
web_1       |   File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
web_1       |     utility.execute()
web_1       |   File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute
web_1       |     django.setup()
web_1       |   File "/usr/local/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
web_1       |     apps.populate(settings.INSTALLED_APPS)
web_1       |   File "/usr/local/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
web_1       |     app_config = AppConfig.create(entry)
web_1       |   File "/usr/local/lib/python2.7/site-packages/django/apps/config.py", line 94, in create
web_1       |     module = import_module(entry)
web_1       |   File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
web_1       |     __import__(name)
web_1       | ImportError: No module named  cabot_alert_telegram
```

what am i doing wrong?

**Comment by frankh** [comment]
It looks like the problem's caused by the space in the environment variable - it's trying to import ` cabot_alert_telegram` (with a space in front)

**Comment by frankh** [comment]
Please reopen if you're still having issues
